### PR TITLE
use redirect hostname to lookup realm for correct mobile app

### LINKED ISSUE #779: enx-redreict
incorrect app ownership shown in .well-known/assetlinks.json

if none is set, something is still present.

/kind bug
/assign

### PR DESCRIPTION
**Pull request by mikehelmick**
Fixes #779

## Proposed Changes

* use hostname when deciding what mobile app config to serve on .well-known
* if no configuration, serve a 404
* make cache TTL configurable

**Release Note**

```release-note
BUGFIX: Ensure that .well-known is served for the correct region.
```

### CODE REVIEW

File: pkg/database/realm.go [hunk 1]
```diff
@@ -716,6 +716,18 @@ func (db *Database) CreateRealm(name string) (*Realm, error) {
 	return realm, nil
 }
 
+func (db *Database) FindRealmByRegion(region string) (*Realm, error) {
```
Comment (sethvargo) [inline pkg/database/realm.go:719]: I've moved us<sup>1</sup> away from database lookup functions returning nil because it tends to lead to NPEs. I'd like this to return an error instead, and then the controller should use `database.IsNotFound` to flow control.

<sup>1. </sup> The exception is when the function returns a list. In that case, the empty list (but NOT an uninitialized list) is returned.

File: pkg/database/mobile_app.go [hunk 2]
```diff
@@ -136,12 +136,12 @@ func (a *MobileApp) BeforeSave(tx *gorm.DB) error {
 }
 
 // ListActiveAppsByOS finds all mobile apps by their OS.
-func (db *Database) ListActiveAppsByOS(os OSType) ([]*MobileApp, error) {
+func (db *Database) ListActiveAppsByOS(realmID uint, os OSType) ([]*MobileApp, error) {
```
Comment (sethvargo) [inline pkg/database/mobile_app.go:139]: Update comment

**Review by sethvargo — CHANGES_REQUESTED** [review]

File: pkg/controller/associated/android.go [hunk 3]
```diff
@@ -33,8 +33,13 @@ type Target struct {
 }
 
 // getAndroidData finds all the android data apps.
-func (c *Controller) getAndroidData() ([]AndroidData, error) {
-	apps, err := c.db.ListActiveAppsByOS(database.OSTypeAndroid)
+func (c *Controller) getAndroidData(region string) ([]AndroidData, error) {
+	realm, err := c.db.FindRealmByRegion(region)
+	if err != nil {
+		return nil, fmt.Errorf("unable to lookup realm")
```
Comment (sethvargo) [inline pkg/controller/associated/android.go:39]:
```suggestion
		return nil, fmt.Errorf("unable to lookup realm: %w", err)
```

File: pkg/controller/associated/ios.go [hunk 4]
```diff
@@ -62,15 +66,21 @@ func (c *Controller) getAppIds() ([]string, error) {
 }
 
 // getIosData gets the iOS app data.
-func (c *Controller) getIosData() (*IOSData, error) {
-	var ids []string
-	var err error
+func (c *Controller) getIosData(region string) (*IOSData, error) {
+	realm, err := c.db.FindRealmByRegion(region)
+	if err != nil {
+		return nil, fmt.Errorf("unable to lookup realm")
```
Comment (sethvargo) [inline pkg/controller/associated/ios.go:72]:
```suggestion
		return nil, fmt.Errorf("unable to lookup realm: %w", err)
```

**Review by sethvargo — APPROVED** [review]
Nits, but can be a follow up
