### PR TITLE
SMS Deep links and settings

### LINKED ISSUE #138: Is the length of the verification code configurable or hardcoded ?
Is the length of the verification code configurable or hardcoded ? i.e through an env variable

### LINKED ISSUE #143: Realm admin / config
- Implement UI for creating / updating realms
- Implement realm specific settings UI

Necessary for customization - and settings for the realm.
Needed for #138 #117 #134 

/assign

### LINKED ISSUE #213: error in database migration after latest update
Updating from pre-Realm setup the database migration failed : 

```
Step #1 - "migrate": (/workspace/pkg/database/migrations.go:239)
Step #1 - "migrate": [2020-08-10 02:51:02]  pq: duplicate key value violates unique constraint "uix_realms_name"
Step #1 - "migrate": {"severity":"error","ts":1597027862.3047037,"logger":"default","caller":"database/migrations.go:519","message":"database migrations failed: pq: duplicate key value violates unique constraint \"uix_realms_name\"","stacktrace":"github.com/google/exposure-notifications-verification-server/pkg/database.(*Database).MigrateTo\n\t/workspace/pkg/database/migrations.go:519\nmain.realMain\n\t/workspace/cmd/migrate/main.go:58\nmain.main\n\t/workspace/cmd/migrate/main.go:36\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
Step #1 - "migrate": {"severity":"info","ts":1597027862.3055081,"logger":"default","caller":"migrate/main.go:43","message":"migrations complete"}
```

@mikehelmick

### PR DESCRIPTION
**Pull request by mikehelmick**
Fixes #138
Fixes #143
Fixes #213 

## Proposed Changes

* add region designator for a realm, i.e. `US-WA`
* Generate both 'short' and 'long' codes
 * short codes have shorter timeouts and are meant to read over the phone, long codes only over SMS
 * long codes are alphamumeric a-v,0-9
* Option to use deep links for codes in SMS
 * for example `ens://v?r=US-WA&c=ABCD1234`
* add all of these settings into the realm setting page

image

**Release Note**

```release-note
Short and long verification codes issued at the same time. Long codes can be valid for up to 24 hours. Option to generate a SMS 'deeplink' to make it so the code doesn't need to be copied / retyped. Settings screen for realm settings.
```

### CODE REVIEW

File: pkg/database/realm.go [hunk 1]
```diff
@@ -42,6 +48,19 @@ type Realm struct {
 	// Name is the name of the realm.
 	Name string `gorm:"type:varchar(200);unique_index"`
 
+	// Code configuration
+	RegionCode              string `gorm:"type:varchar(5); not null; default: ''"`
```
Comment (sethvargo) [inline pkg/database/realm.go:52]: NOT NULL with a default of empty string feels weird

File: pkg/database/realm.go [hunk 2]
```diff
@@ -42,6 +48,19 @@ type Realm struct {
...
+	CodeLength              uint   `gorm:"type:smallint; not null; default: 8"`
+	CodeDurationSeconds     int64  `gorm:"type:bigint; not null; default: 900"` // default 15m (in seconds)
```
Comment (sethvargo) [inline pkg/database/realm.go:54]: The max for integer is 2147483647. 2147483647 is ~70 years. bigint is 9223372036854775807 which is 2924712086 _centuries_. I think we can use integer here 😄

File: pkg/database/realm.go [hunk 3]
```diff
@@ -42,6 +48,19 @@ type Realm struct {
...
+	UseSMSLongCodes         bool   `gorm:"type:boolean; not null; default: true"`
+	LongCodeLength          uint   `gorm:"type:smallint; not null; default: 16"`
+	LongCodeDurationSeconds int64  `gorm:"type:bigint; not null; default: 86400"` // default 24h
```
Comment (sethvargo) [inline pkg/database/realm.go:57]: integer

File: pkg/database/realm.go [hunk 4]
```diff
@@ -42,6 +48,19 @@ type Realm struct {
...
+	// SMS Content
+	DeepLinkProtocol string `gorm:"type:varchar(50); not null; default: 'ens://v?'"`
+	DeepLinkRegion   bool   `gorm:"type:boolean; not null; default: true"`
```
Comment (sethvargo) [inline pkg/database/realm.go:60]: I've had a lot of problems with gorm and boolean types. This is another reason I vote for making an arbitrary template field the admin can provide.

File: pkg/database/realm.go [hunk 5]
```diff
@@ -55,22 +74,77 @@ type Realm struct {
 	// Relations to items that belong to a realm.
 	Codes  []*VerificationCode `gorm:"PRELOAD:false; SAVE_ASSOCIATIONS:false; ASSOCIATION_AUTOUPDATE:false, ASSOCIATION_SAVE_REFERENCE:false"`
 	Tokens []*Token            `gorm:"PRELOAD:false; SAVE_ASSOCIATIONS:false; ASSOCIATION_AUTOUPDATE:false, ASSOCIATION_SAVE_REFERENCE:false"`
+
+	// Populated by AfterFind
+	codeDuration     time.Duration
```
Comment (sethvargo) [inline pkg/database/realm.go:79]: I think it'd be better to define a custom `time.Duration` type and define the sql package scanner:

```
type Duration time.Duration

func (d Duration) Value() (driver.Value, error) {
    return driver.Value(int64(d)), nil
}

func (d *Duration) Scan(raw interface{}) error {
    switch v := raw.(type) {
    case int64:
        *d = Duration(v)
    case nil:
        *d = Duration(0)
    default:
        return fmt.Errorf("unknown duration type: %T", raw)
    }
    return nil
}

// 
LongCodeDuration Duration
```

Gorm uses go/sql under the hood, so it should work.

File: pkg/database/realm.go [hunk 6]
```diff
@@ -55,22 +74,77 @@ type Realm struct {
...
+		LongCodeLength:          16,
+		LongCodeDurationSeconds: 86400,
+		DeepLinkProtocol:        "ens://v?",
+		DeepLinkRegion:          true,
+		SMSTextGreeting:         "This is your Exposure Notifications Verification code:",
+		AllowedTestTypes:        14,
+	}
+}
+
+func (r *Realm) AfterFind(tx *gorm.DB) error {
```
Comment (sethvargo) [inline pkg/database/realm.go:100]: If you keep this vs a custom scanner interface, doc

File: pkg/database/realm.go [hunk 7]
```diff
@@ -55,22 +74,77 @@ type Realm struct {
...
+		r.AddError("codeDurationSeconds", "must be no more than 1 hour")
+	}
+
 	if len(r.Errors()) > 0 {
 		return fmt.Errorf("validation failed")
 	}
 	return nil
 }
 
+func (r *Realm) GetCodeDuration() time.Duration {
```
Comment (sethvargo) [inline pkg/database/realm.go:128]: All four of these Go away if you use the customer scanner 😉

File: pkg/database/vercode.go [hunk 8]
```diff
@@ -75,36 +77,53 @@ func (v *VerificationCode) FormatSymptomDate() string {
 	return v.SymptomDate.Format("2006-01-02")
 }
 
+// IsCodeExpired checks to see if the actual code provides is the
+// short or long code and deteriminies if it is expired based on that.
+func (v *VerificationCode) IsCodeExpired(code string) bool {
+	now := time.Now()
```
Comment (sethvargo) [inline pkg/database/vercode.go:83]: Should we be UTC-ing these?

File: pkg/database/vercode.go [hunk 9]
```diff
@@ -75,36 +77,53 @@ func (v *VerificationCode) FormatSymptomDate() string {
...
+	if v.Code == code {
+		return !v.ExpiresAt.After(now)
+	}
+	return !v.LongExpiresAt.After(now)
```
Comment (sethvargo) [inline pkg/database/vercode.go:87]: I understand what's going on here, but it's a little clever. Maybe:

```go
switch code {
  case v.Code:
    return !v.ExpiresAt.After(now)
  case v.LongCode:
    return !v.LongExpiresAt.After(now)
  default:
    return false
}
```

File: pkg/otp/code.go [hunk 10]
```diff
@@ -45,40 +52,68 @@ func GenerateCode(length uint) (string, error) {
 	return result, nil
 }
 
+// GenerateAlphanumericCode will generate an alpha numberic code.
```
Comment (sethvargo) [inline pkg/otp/code.go:55]: We should _probably_ use sethvargo/go-password here instead. That was reviewed by ISE and bradfitz.

File: cmd/server/assets/realm.html [hunk 11]
```diff
@@ -41,6 +41,23 @@ <h1>Realm settings</h1>
...
+            <div class="col-sm-9">
+              <input type="text" id="regionCode" name="regionCode" class="form-control{{if $realm.ErrorsFor "regionCode"}} is-invalid{{end}}" value="{{$realm.RegionCode}}" />
+              {{if $realm.ErrorsFor "regionCode"}}
+              <div class="invalid-feedback">
+                {{joinStrings ($realm.ErrorsFor "regionCode") ", "}}
+              </div>
+              {{end}}
+              <small class="form-text text-muted">
+                Used in creating deep link SMS for multi-helath authority apps. Region should
+                be ISO 3166-1 country codes and ISO 3166-2 subdivision codes where applicable.
```
[the remark this answers is not in the document]
Comment (mikehelmick) [reply cmd/server/assets/realm.html:55]: linked to wikipedia

File: cmd/server/assets/realm.html [hunk 12]
```diff
@@ -88,6 +105,157 @@ <h1>Realm settings</h1>
...
+      <div class="card mb-3">
+        <div class="card-header">
+          Verification code configuration
+        </div>
+        <div class="card-body">
+          <div class="form-group row">
+            <label for="codeLength" class="col-sm-3">Code length:</label>
+            <div class="col-sm-9">
+              <select class="form-control{{if $realm.ErrorsFor "codeLength"}} is-invalid{{end}}" name="codeLength" id="codeLength">
+                {{range $cl := .shortCodeLengths}}
```
[the remark this answers is not in the document]
Comment (mikehelmick) [reply cmd/server/assets/realm.html:117]: The current setting for your realm is pre-selected already, I think that's necessary since this isn't just a create, but an update.

File: cmd/server/assets/realm.html [hunk 13]
```diff
@@ -88,6 +105,157 @@ <h1>Realm settings</h1>
         </div>
       </div>
 
+      <div class="card mb-3">
+        <div class="card-header">
+          Verification code configuration
+        </div>
+        <div class="card-body">
+          <div class="form-group row">
+            <label for="codeLength" class="col-sm-3">Code length:</label>
```
[the remark this answers is not in the document]
Comment (mikehelmick) [reply cmd/server/assets/realm.html:114]: changed to characters - does that look better?

File: pkg/database/vercode.go (hunk 8 above)
Comment (mikehelmick) [reply pkg/database/vercode.go:83]: technically, I don't think it matters since time managed time zones, but it's good hygiene.

File: pkg/database/vercode.go (hunk 9 above)
Comment (mikehelmick) [reply pkg/database/vercode.go:87]: either, way. changed it to switch, but the default should be true (expired)

File: pkg/otp/code.go (hunk 10 above)
Comment (mikehelmick) [reply pkg/otp/code.go:53]: that didn't quite have what I wanted - I did make this better though using that as a basis.

**Comment by mikehelmick** [comment]
Updated - SMS settings now included a template w/ 5 replacements

image

File: cmd/server/assets/realm.html (hunk 13 above)
[the remark this answers is not in the document]
Comment (sethvargo) [reply cmd/server/assets/realm.html]: yup
