### PR TITLE
legacy signing fixes

### LINKED ISSUE #1623: tokens signed w/ legacy key fail to validate if no DB keys exist`
/assign

### PR DESCRIPTION
**Pull request by mikehelmick**
Fixes #1623

## Proposed Changes

* allow for tokens to be signed w/ legacy keys until DB one is present
   * can be disabled by flag
   * to be removed in v0.21
* fix bug where a not found on DB backed key lookup returned error instead of validating w/ legacy key
* debug logging by default in some tools - makes life easier

**Release Note**

```release-note
Allow for legacy signing key config for tokens to be used during the upgrade to DB backed tokens.
```

### CODE REVIEW

File: pkg/controller/certapi/certapi.go [hunk 1]
```diff
@@ -95,8 +95,9 @@ func (c *Controller) validateToken(ctx context.Context, verToken string) (string
 					return nil, fmt.Errorf("no key corresponds to kid %q", kid)
 				}
 				tokenSigningKey = &database.TokenSigningKey{KeyVersionID: keyID}
+			} else {
+				return nil, fmt.Errorf("failed to lookup token signing key: %w", err)
```
Comment (mikehelmick) [inline pkg/controller/certapi/certapi.go:99]: this was the bug - it filled in legacy key ID, but then returned an error.

File: tools/get-certificate/main.go [hunk 2]
```diff
@@ -41,6 +42,9 @@ func main() {
 
 	ctx, done := signalcontext.OnInterrupt()
 
+	if os.Getenv("LOG_LEVEL") == "" {
```
Comment (sethvargo) [inline tools/get-certificate/main.go:45]: It’d be better just to use the debugger logger instead of setting the env. Just don’t use logging.NewFromEnv and use the NewDebug method (I think there’s one)

**Review by sethvargo — COMMENTED** [review]
I’m not convinced the envvar buys us anything here? I think we should just fallback without the additional layer of indirection and remove in the next release

**Comment by mikehelmick** [comment]
> I’m not convinced the envvar buys us anything here? I think we should just fallback without the additional layer of indirection and remove in the next release

meaning remove the flag?

**Comment by sethvargo** [comment]
Yea, I think we just always fallback in this release.

File: tools/get-certificate/main.go (hunk 2 above)
Comment (mikehelmick) [reply tools/get-certificate/main.go:45]: this still allows the user to specify

**Comment by mikehelmick** [comment]
> Yea, I think we just always fallback in this release.

done. Always on in this release.

**Review by sethvargo — APPROVED** [review]
